//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Link.Multicanal.API.Multicanal.WebService.ServidorSms
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gms.es/", ConfigurationName="Multicanal.WebService.ServidorSms.AddServicePortType")]
    public interface AddServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/envioSmsDirecto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.envioSmsDirectoResponse envioSmsDirecto(Multicanal.WebService.ServidorSms.envioSmsDirectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/envioSmsDirecto", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.envioSmsDirectoResponse> envioSmsDirectoAsync(Multicanal.WebService.ServidorSms.envioSmsDirectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/envioSmsDirecto02", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.envioSmsDirecto02Response envioSmsDirecto02(Multicanal.WebService.ServidorSms.envioSmsDirecto02Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/envioSmsDirecto02", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.envioSmsDirecto02Response> envioSmsDirecto02Async(Multicanal.WebService.ServidorSms.envioSmsDirecto02Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultaEstadoSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.consultaEstadoSmsResponse consultaEstadoSms(Multicanal.WebService.ServidorSms.consultaEstadoSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultaEstadoSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultaEstadoSmsResponse> consultaEstadoSmsAsync(Multicanal.WebService.ServidorSms.consultaEstadoSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultaSmsDirecto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.consultaSmsDirectoResponse consultaSmsDirecto(Multicanal.WebService.ServidorSms.consultaSmsDirectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultaSmsDirecto", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultaSmsDirectoResponse> consultaSmsDirectoAsync(Multicanal.WebService.ServidorSms.consultaSmsDirectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultaHLR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.consultaHLRResponse consultaHLR(Multicanal.WebService.ServidorSms.consultaHLRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultaHLR", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultaHLRResponse> consultaHLRAsync(Multicanal.WebService.ServidorSms.consultaHLRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/crearConsultaHLRMas" +
            "iva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaResponse crearConsultaHLRMasiva(Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/crearConsultaHLRMas" +
            "iva", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaResponse> crearConsultaHLRMasivaAsync(Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/estadoConsultaHLRMa" +
            "siva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaResponse estadoConsultaHLRMasiva(Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/estadoConsultaHLRMa" +
            "siva", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaResponse> estadoConsultaHLRMasivaAsync(Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/descargarConsultaHL" +
            "RMasiva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaResponse descargarConsultaHLRMasiva(Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/descargarConsultaHL" +
            "RMasiva", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaResponse> descargarConsultaHLRMasivaAsync(Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultarSaldoSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Multicanal.WebService.ServidorSms.consultarSaldoSmsResponse consultarSaldoSms(Multicanal.WebService.ServidorSms.consultarSaldoSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.linkmobility.es/webservice/servidorSms.php/consultarSaldoSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultarSaldoSmsResponse> consultarSaldoSmsAsync(Multicanal.WebService.ServidorSms.consultarSaldoSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envioSmsDirecto", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class envioSmsDirectoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string idCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string departamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string destinatario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string remitente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string charset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string texto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string solicitarDR;
        
        public envioSmsDirectoRequest()
        {
        }
        
        public envioSmsDirectoRequest(string login, string password, string idCuenta, string departamento, string referencia, string destinatario, string remitente, string charset, string texto, string solicitarDR)
        {
            this.login = login;
            this.password = password;
            this.idCuenta = idCuenta;
            this.departamento = departamento;
            this.referencia = referencia;
            this.destinatario = destinatario;
            this.remitente = remitente;
            this.charset = charset;
            this.texto = texto;
            this.solicitarDR = solicitarDR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envioSmsDirectoResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class envioSmsDirectoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string refWeb;
        
        public envioSmsDirectoResponse()
        {
        }
        
        public envioSmsDirectoResponse(string resultado, string descripcion, string refWeb)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.refWeb = refWeb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envioSmsDirecto02", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class envioSmsDirecto02Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string idCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string departamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string destinatario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string remitente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string charset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string texto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string solicitarDR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string expiracion;
        
        public envioSmsDirecto02Request()
        {
        }
        
        public envioSmsDirecto02Request(string login, string password, string idCuenta, string departamento, string referencia, string destinatario, string remitente, string charset, string texto, string solicitarDR, string expiracion)
        {
            this.login = login;
            this.password = password;
            this.idCuenta = idCuenta;
            this.departamento = departamento;
            this.referencia = referencia;
            this.destinatario = destinatario;
            this.remitente = remitente;
            this.charset = charset;
            this.texto = texto;
            this.solicitarDR = solicitarDR;
            this.expiracion = expiracion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envioSmsDirecto02Response", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class envioSmsDirecto02Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string refWeb;
        
        public envioSmsDirecto02Response()
        {
        }
        
        public envioSmsDirecto02Response(string resultado, string descripcion, string refWeb)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.refWeb = refWeb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaEstadoSms", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultaEstadoSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string idCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string referenciaSms;
        
        public consultaEstadoSmsRequest()
        {
        }
        
        public consultaEstadoSmsRequest(string login, string password, string idCuenta, string referenciaSms)
        {
            this.login = login;
            this.password = password;
            this.idCuenta = idCuenta;
            this.referenciaSms = referenciaSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaEstadoSmsResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultaEstadoSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string estado;
        
        public consultaEstadoSmsResponse()
        {
        }
        
        public consultaEstadoSmsResponse(string resultado, string descripcion, string estado)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaSmsDirecto", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultaSmsDirectoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string idCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string referenciaSms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string destino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string referenciaCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string departamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string filtro;
        
        public consultaSmsDirectoRequest()
        {
        }
        
        public consultaSmsDirectoRequest(string login, string password, string idCuenta, string fechaInicio, string fechaFin, string referenciaSms, string destino, string referenciaCliente, string departamento, string filtro)
        {
            this.login = login;
            this.password = password;
            this.idCuenta = idCuenta;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.referenciaSms = referenciaSms;
            this.destino = destino;
            this.referenciaCliente = referenciaCliente;
            this.departamento = departamento;
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaSmsDirectoResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultaSmsDirectoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string registros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string datos;
        
        public consultaSmsDirectoResponse()
        {
        }
        
        public consultaSmsDirectoResponse(string resultado, string descripcion, string registros, string datos)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.registros = registros;
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaHLR", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultaHLRRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string numero;
        
        public consultaHLRRequest()
        {
        }
        
        public consultaHLRRequest(string login, string password, string numero)
        {
            this.login = login;
            this.password = password;
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaHLRResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultaHLRResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string refWeb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string idGms;
        
        public consultaHLRResponse()
        {
        }
        
        public consultaHLRResponse(string resultado, string descripcion, string refWeb, string idGms)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.refWeb = refWeb;
            this.idGms = idGms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearConsultaHLRMasiva", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class crearConsultaHLRMasivaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string nombreLista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] lista;
        
        public crearConsultaHLRMasivaRequest()
        {
        }
        
        public crearConsultaHLRMasivaRequest(string login, string password, string nombreLista, byte[] lista)
        {
            this.login = login;
            this.password = password;
            this.nombreLista = nombreLista;
            this.lista = lista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearConsultaHLRMasivaResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class crearConsultaHLRMasivaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string refWeb;
        
        public crearConsultaHLRMasivaResponse()
        {
        }
        
        public crearConsultaHLRMasivaResponse(string resultado, string descripcion, string refWeb)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.refWeb = refWeb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estadoConsultaHLRMasiva", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class estadoConsultaHLRMasivaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string refWeb;
        
        public estadoConsultaHLRMasivaRequest()
        {
        }
        
        public estadoConsultaHLRMasivaRequest(string login, string password, string refWeb)
        {
            this.login = login;
            this.password = password;
            this.refWeb = refWeb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estadoConsultaHLRMasivaResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class estadoConsultaHLRMasivaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string estado;
        
        public estadoConsultaHLRMasivaResponse()
        {
        }
        
        public estadoConsultaHLRMasivaResponse(string resultado, string descripcion, string estado)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="descargarConsultaHLRMasiva", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class descargarConsultaHLRMasivaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string refWeb;
        
        public descargarConsultaHLRMasivaRequest()
        {
        }
        
        public descargarConsultaHLRMasivaRequest(string login, string password, string refWeb)
        {
            this.login = login;
            this.password = password;
            this.refWeb = refWeb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="descargarConsultaHLRMasivaResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class descargarConsultaHLRMasivaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] datos;
        
        public descargarConsultaHLRMasivaResponse()
        {
        }
        
        public descargarConsultaHLRMasivaResponse(string resultado, string descripcion, byte[] datos)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSaldoSms", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultarSaldoSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public consultarSaldoSmsRequest()
        {
        }
        
        public consultarSaldoSmsRequest(string login, string password)
        {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSaldoSmsResponse", WrapperNamespace="http://www.gms.es/", IsWrapped=true)]
    public partial class consultarSaldoSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string saldo;
        
        public consultarSaldoSmsResponse()
        {
        }
        
        public consultarSaldoSmsResponse(string resultado, string descripcion, string saldo)
        {
            this.resultado = resultado;
            this.descripcion = descripcion;
            this.saldo = saldo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AddServicePortTypeChannel : Multicanal.WebService.ServidorSms.AddServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AddServicePortTypeClient : System.ServiceModel.ClientBase<Multicanal.WebService.ServidorSms.AddServicePortType>, Multicanal.WebService.ServidorSms.AddServicePortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AddServicePortTypeClient() : 
                base(AddServicePortTypeClient.GetDefaultBinding(), AddServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AddServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(AddServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), AddServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AddServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AddServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AddServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Multicanal.WebService.ServidorSms.envioSmsDirectoResponse envioSmsDirecto(Multicanal.WebService.ServidorSms.envioSmsDirectoRequest request)
        {
            return base.Channel.envioSmsDirecto(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.envioSmsDirectoResponse> envioSmsDirectoAsync(Multicanal.WebService.ServidorSms.envioSmsDirectoRequest request)
        {
            return base.Channel.envioSmsDirectoAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.envioSmsDirecto02Response envioSmsDirecto02(Multicanal.WebService.ServidorSms.envioSmsDirecto02Request request)
        {
            return base.Channel.envioSmsDirecto02(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.envioSmsDirecto02Response> envioSmsDirecto02Async(Multicanal.WebService.ServidorSms.envioSmsDirecto02Request request)
        {
            return base.Channel.envioSmsDirecto02Async(request);
        }
        
        public Multicanal.WebService.ServidorSms.consultaEstadoSmsResponse consultaEstadoSms(Multicanal.WebService.ServidorSms.consultaEstadoSmsRequest request)
        {
            return base.Channel.consultaEstadoSms(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultaEstadoSmsResponse> consultaEstadoSmsAsync(Multicanal.WebService.ServidorSms.consultaEstadoSmsRequest request)
        {
            return base.Channel.consultaEstadoSmsAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.consultaSmsDirectoResponse consultaSmsDirecto(Multicanal.WebService.ServidorSms.consultaSmsDirectoRequest request)
        {
            return base.Channel.consultaSmsDirecto(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultaSmsDirectoResponse> consultaSmsDirectoAsync(Multicanal.WebService.ServidorSms.consultaSmsDirectoRequest request)
        {
            return base.Channel.consultaSmsDirectoAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.consultaHLRResponse consultaHLR(Multicanal.WebService.ServidorSms.consultaHLRRequest request)
        {
            return base.Channel.consultaHLR(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultaHLRResponse> consultaHLRAsync(Multicanal.WebService.ServidorSms.consultaHLRRequest request)
        {
            return base.Channel.consultaHLRAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaResponse crearConsultaHLRMasiva(Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaRequest request)
        {
            return base.Channel.crearConsultaHLRMasiva(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaResponse> crearConsultaHLRMasivaAsync(Multicanal.WebService.ServidorSms.crearConsultaHLRMasivaRequest request)
        {
            return base.Channel.crearConsultaHLRMasivaAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaResponse estadoConsultaHLRMasiva(Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaRequest request)
        {
            return base.Channel.estadoConsultaHLRMasiva(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaResponse> estadoConsultaHLRMasivaAsync(Multicanal.WebService.ServidorSms.estadoConsultaHLRMasivaRequest request)
        {
            return base.Channel.estadoConsultaHLRMasivaAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaResponse descargarConsultaHLRMasiva(Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaRequest request)
        {
            return base.Channel.descargarConsultaHLRMasiva(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaResponse> descargarConsultaHLRMasivaAsync(Multicanal.WebService.ServidorSms.descargarConsultaHLRMasivaRequest request)
        {
            return base.Channel.descargarConsultaHLRMasivaAsync(request);
        }
        
        public Multicanal.WebService.ServidorSms.consultarSaldoSmsResponse consultarSaldoSms(Multicanal.WebService.ServidorSms.consultarSaldoSmsRequest request)
        {
            return base.Channel.consultarSaldoSms(request);
        }
        
        public System.Threading.Tasks.Task<Multicanal.WebService.ServidorSms.consultarSaldoSmsResponse> consultarSaldoSmsAsync(Multicanal.WebService.ServidorSms.consultarSaldoSmsRequest request)
        {
            return base.Channel.consultarSaldoSmsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AddServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AddServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.linkmobility.es/webservice/servidorSms.php");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AddServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.AddServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AddServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.AddServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            AddServicePort,
        }
    }
}
